### ISSUE TITLE
[proposal] uniform naming for read roads funcs in `utils.py`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#104]
I'd like to adjust the naming of the read roads functions in `utils.py` for uniformity.
* [`read_parquet_roads()`](https://github.com/uscuni/simplification/blob/f8939a869115cc131dca331d129b52ca1950eac6/core/utils.py#L55C5-L55C23) --> `read_original()`
* [`read_no_degree_2_roads()`](https://github.com/uscuni/simplification/blob/f8939a869115cc131dca331d129b52ca1950eac6/core/utils.py#L66) --> `read_no_degree_2()`
* [`read_manual()`](https://github.com/uscuni/simplification/blob/f8939a869115cc131dca331d129b52ca1950eac6/core/utils.py#L74C5-L74C16) --> no change
* [`read_parenx()`](https://github.com/uscuni/simplification/blob/f8939a869115cc131dca331d129b52ca1950eac6/core/utils.py#L86) --> no change

Any detractors?

@anastassiavybornova @martinfleis

**Comment by anastassiavybornova** [comment]
fine with me!
