### ISSUE TITLE
[proposal] move & rename `roads_osm.parquet`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#105]
To conform with [other roads data](https://github.com/uscuni/simplification/tree/main/data) I'd like to move & rename the `roads_osm.parquet` files as follows:
* `data/<FUA>/roads_osm.parquet` --> `data/<FUA>/original/<FUA>.parquet`

xref #104 

Any detractors?

@anastassiavybornova @martinfleis

**Comment by martinfleis** [comment]
fine with that
