### ISSUE TITLE
`read_artifacts()` utility for reading in `data/FUA/polygons/`?

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#107]
Is there desire for a `read_artifacts()` utility function for reading in the `data/FUA/polygons/` parquet files?

@anastassiavybornova @martinfleis

**Comment by anastassiavybornova** [comment]
hmmm i think right now we're only loading the `roads` files and deriving the artifact polygons with momepy on the go (which is also mimicking the general case we assume, where the info is a gdf of linestrings), so i would say we don't need a separate function for reading in artifacts, but let's see what Martin says

**Comment by martinfleis** [comment]
Same. No need for a utility here.
