### ISSUE TITLE
network preprocessing

### ISSUE THREAD

**Issue by martinfleis** [uscuni/simplification#109]
This is what we do now based on the original road networks before doing anything with it

```py
roads = momepy.remove_false_nodes(roads)
roads = roads[~roads.geometry.duplicated()].reset_index()
roads = momepy.remove_false_nodes(roads)
```

I believe that the Parquet versions of "no node 2" networks should be an output of this, not just a single `remove_false_nodes` run.

**Comment by jGaboardi** [comment]
OK, so I will update #80 with:
* refactored [`remove_degree_2_nodes()`](https://github.com/uscuni/simplification/blob/b00cf61f96277801afd66a3d93c8e0e59c6d54fa/core/utils.py#L173)
* re-generated [`data/*/no_degree_2.parquet`](https://github.com/uscuni/simplification/tree/main/data)
* adjusted tests as needed.
* Seems I should remove [this chunk](https://github.com/uscuni/simplification/pull/80/files#diff-62860237333e9226a4b65fd9518abc0dc12c792aefe2d057f04685a976ba3eceR29-R30) from `common.continuity()`, correct?

Let me know how this sounds

**Comment by martinfleis** [comment]
> Seems I should remove [this chunk](https://github.com/uscuni/simplification/pull/80/files#diff-62860237333e9226a4b65fd9518abc0dc12c792aefe2d057f04685a976ba3eceR29-R30) from common.continuity(), correct?

Yeah, that will be redundant.

**Comment by jGaboardi** [comment]
We want to drop or keep the index after resetting in line 2?

```python
roads = momepy.remove_false_nodes(roads)
roads = roads[~roads.geometry.duplicated()].reset_index()
roads = momepy.remove_false_nodes(roads)
```

**Comment by martinfleis** [comment]
Reset. We don't care.

**Comment by jGaboardi** [comment]
Resolving #80
