### ISSUE TITLE
post-workshop todos

### ISSUE THREAD

**Issue by anastassiavybornova** [uscuni/simplification#115]
**singletons:**

all done

**doubles:**

* preserve attributes (CES logic) within `remove_false_nodes`, pass them to singleton solution so it doesn't get overwritten
* include loop where doubles which have C in the middle are treated (no code yet) - just take half of those, call singleton solution, recompute coins, solve other half
* combine it all in the end

**clusters:**

* first, solve non-plannar reconnections (xref #116 )
* then, integrate function from n-clusters branch (clusters) into rest of workflow

**workflow:**

* we will have 3 functions (1, 2, many)
* wrap into single function that does split and calls in sequence
* in the end we want: singlefunction(streetnetwork) that solves face artifact detection, classification/typology, simplification, and returns finished network
* documentation for insiders

**packaging:**
* discuss with james

**future feature requests:**

* smoothening out of bumps
* dangling improvement
* optimally preserving attributes

**Comment by martinfleis** [comment]
Making a note for myself to look at this gap in Auckland 
<img width="850" alt="Screenshot 2024-07-30 at 22 04 24" src="https://github.com/user-attachments/assets/b1e9f8fe-761d-4ae1-a2b7-cb511d044118">

**Comment by jGaboardi** [comment]
I think this can be closed out. If not, we can reopen and transfer to `sgeop`.
