### ISSUE TITLE
reconsider artifact clusters that touch network in only 1 place (edge)

### ISSUE THREAD

**Issue by anastassiavybornova** [uscuni/simplification#117]
find more examples for this in n-artifact clusters.

"The issue is that it does not go to nx_gx where it would use the dangle solution but straight to the skeleton since these two don't agree on what the interline is (top thinks it is C, bottom knows it is S)." -- suggestion: "if one of the artifact pairs neighbours only the other and nothing else from the network, we fall back to interstitial node removal."

**Comment by anastassiavybornova** [comment]
@martinfleis i think we can close this one too?

**Comment by martinfleis** [comment]
I think I've done something on this? Can't tell from memory.

**Comment by anastassiavybornova** [comment]
if i remember correctly: those were the artifact clusters were artifacts are "piling up" on top of each other, with only one of them touching the network. i can't remember what the solution was but i can remember that this got solved, as in, we don't get problems with these anymore? :)

**Comment by martinfleis** [comment]
Yeah, I think I solved this.

**Comment by jGaboardi** [comment]
I will close. Please reopen if I am jumping the gun.
