### ISSUE TITLE
Develop extension of bananas

### ISSUE THREAD

**Issue by martinfleis** [uscuni/simplification#118]
We're missing quite a bit of polygons along highways in our detection. I think that we should figure out some smart way of expanding it. We now do 1% over the threshold if they are adjacent but I think that we'll need to go deeper and allow extension with lower circular compactness to go beyond that 1%. Haven't looked into that yet but the most striking issues in the result are due to missing artifacts where I would expect them.

**Comment by martinfleis** [comment]
For some reason, the way we do it now does not detect artifacts properly in Salt Lake City. Only 277 get detected, I sense some issue with peaks.

**Comment by anastassiavybornova** [comment]
* try: focus on circular compactness - polygons that are very elongated
* mostly salt lake city. more artifacts than urban blocks - does the number matter?

**Comment by anastassiavybornova** [comment]
@martinfleis the salt lake city one is solved by not using service roads, but i wonder whether we should keep this open to integrate the future final version of `get_artifacts` into `FaceArtifacts`, too?

**Comment by martinfleis** [comment]
Let's keep this open for now.

**Comment by martinfleis** [comment]
I think this is mostly solved now. The rest can be left to #134
