### ISSUE TITLE
Identify case studies

### ISSUE THREAD

**Issue by martinfleis** [uscuni/simplification#12]

**Comment by anastassiavybornova** [comment]
we now have the following case study (continents) cities [FUA ID]:
* (Africa) Douala [809]
* (Asia) Aleppo [1133]
* (South America) Bucaramanga [4617]
* (North America) Salt Lake City [4881]
* (Europe) Liège [1656]
* (Oceania) Auckland [869]

Ideally, let's run our workflows (momepy/osmnx/cityseer) on each of those 6 to make sure that they make sense case study wise before closing this issue

**Comment by martinfleis** [comment]
Somehow I thought the number in the brackets is the number of artifacts 🙃
