### ISSUE TITLE
rerun parenx simplification

### ISSUE THREAD

**Issue by martinfleis** [uscuni/simplification#130]
We need to rerun parenx simplification following #127

**Comment by jGaboardi** [comment]
https://github.com/uscuni/simplification/issues/131#issuecomment-2295291251

**Comment by anastassiavybornova** [comment]
WIP on the https://github.com/uscuni/simplification/tree/parenx-rerun branch (haven't finished it yet :-/ there seems to be a shapely bug to uncover. will try to look at it this week)

**Comment by anastassiavybornova** [comment]
...and confirm that correct input data is being used, to prevent issues like this one

![image](https://github.com/user-attachments/assets/2ef89a2a-c319-4778-8360-f4f4674ebff7)

**Comment by martinfleis** [comment]
no_degree_2 is using stuff implemented in `sgeop` so I'd say original. How did the issue above happened?

**Comment by anastassiavybornova** [comment]
> How did the issue above happened?

not sure, i will rerun evaluation and keep in mind to check whether it persists

**Comment by anastassiavybornova** [comment]
solved by #201
