### ISSUE TITLE
avoid disconnecting voronoi by reducing clipping distance iteratively

### ISSUE THREAD

**Issue by anastassiavybornova** [uscuni/simplification#135]
By having a non-flexible `distance` input to `voronoi_skeleton`, we sometimes get disconnected voronoi components at polygons that are narrow in some places but broad in others, like here:

![image](https://github.com/user-attachments/assets/8085917c-fb5b-44d5-99f3-5b8be9acde14)

--> to aviod this, count nr of components in voronoi skeleton before/after the clipping, and if it increases, reduce distance iteratively until number of comps doesn't increase anymore

**Comment by martinfleis** [comment]
Closed by #137
