### ISSUE TITLE
transfer issues to `sgeop`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#174]
Transfer pertinent issues to [`sgeop `](https://github.com/uscuni/sgeop). Perhaps like the "TODO" issues – uscuni/sgeop#11 , etc.

**Comment by martinfleis** [comment]
Do you have the power to do that?

**Comment by jGaboardi** [comment]
I think so, but let me check.

**Comment by jGaboardi** [comment]
Yes
