### ISSUE TITLE
stuff to keep here vs. `sgeop`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#175]
stuff to keep here vs. `sgeop`

* keep here
  * all code specifically for paper
  * verification stuff
  * comparisons to other packages
     * `osmnx`, `parenex`

**Comment by anastassiavybornova** [comment]
stuff to keep here = basically everything which is here currently except the `core` folder? (and `ci` - not sure?)

**Comment by jGaboardi** [comment]
> basically everything which is here currently except the core folder? (and ci - not sure?)

* We'll be keeping the stuff in `core/` that is exploratory/experiment/publication specific and algorithm specific parts will be sourced from `sgeop`. This will an incremental process while I am getting testing up & running within `sgeop`
* The current version of `ci/` will stay as is. We already pruned that down from `[Ubuntu, macOS, Windows] x [Python-3.11{oldest, latest,dev}]` to only [Ubuntu] x [Python-3.11-latest] in #176 in order to keep barebones testing for our efforts here.
