### ISSUE TITLE
`tobler`/`h3` – AttributeError: module 'h3' has no attribute 'polyfill'

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#181]
* [CI failing from `tobler` -> `h3`](https://github.com/uscuni/simplification/actions/runs/11421701467/job/31778759358#step:7:597)
* see [`core.utils.make_grid()`](https://github.com/uscuni/simplification/blob/9018386eed40ae1f057f9f08386fd74380ce0233/core/utils.py#L150)

```
ERROR core/tests/test_stats.py::test_get_node_stats - AttributeError: module 'h3' has no attribute 'polyfill'
ERROR core/tests/test_stats.py::test_get_edge_stats - AttributeError: module 'h3' has no attribute 'polyfill'
ERROR core/tests/test_viz_h3_hex.py::test_viz_h3_hex_plot_aoi[png] - AttributeError: module 'h3' has no attribute 'polyfill'
ERROR core/tests/test_viz_h3_hex.py::TestVizH3HexPlotCell::test_hex_id[png] - AttributeError: module 'h3' has no attribute 'polyfill'
ERROR core/tests/test_viz_h3_hex.py::TestVizH3HexPlotCell::test_loc_id[png] - AttributeError: module 'h3' has no attribute 'polyfill'
ERROR core/tests/test_viz_h3_hex.py::test_viz_h3_hex_plot_analysis[png] - AttributeError: module 'h3' has no attribute 'polyfill'
FAILED core/tests/test_utils.py::test_make_grid - AttributeError: module 'h3' has no attribute 'polyfill'
============= 1 failed, 46 passed, 14 warnings, 6 errors in 29.61s =============
```

**Comment by jGaboardi** [comment]
This is happening in [`h3-py==4.1.1`](https://github.com/uscuni/simplification/actions/runs/11421701467/job/31778759358#step:5:142) where [`polyfill`](https://github.com/uber/h3-py/blob/3c1d235ac7cf9ec7ebdde1edc427a1f3b20c92ea/src/h3/_cy/__init__.py) not longer seems to be a part of the namespace. I'd say let's pin [`h3-py=<3.7`](https://github.com/uber/h3-py/blob/5871bfb51907841ef08fc085c04a9253e75db87a/src/h3/_cy/__init__.py#L58) where is still a member of the namespace.

**Comment by martinfleis** [comment]
H3 v4 was released. It contains ton of breaking changes with no deprecation period pr any warning. Not a way of doing software updates. Tobler will need a patch. And likely libpysal as we have some h3 tooling there as well.

**Comment by jGaboardi** [comment]
yep... Looking through API changes now... 😵‍💫
