### ISSUE TITLE
reorganize files in /notebooks/

### ISSUE THREAD

**Issue by anastassiavybornova** [uscuni/simplification#182]
as part of working on the evaluation & comparison of different methods: shall we reorganize the files  in `/notebooks/` to make clear which notebooks are part of which workflow?

overview of notebooks we currently have now, grouped by my suggestion of what to do with them:

**obsolete**

* `_addartifacts_8989.ipynb` – this was an extra preprocessing step for Wuhan data, but we are also providing the raw data already
* `_convert.ipynb` - from .parquet to layered .gpkg, tailored to your local file system @martinfleis
* * `check_corrected_input_data.ipynb` - i think this was to double check the service road mess

suggestion for all of them: delete? or move to an `archive` folder?

**preprocessing**

* `_clip_networks.ipynb` – this reduces from full FUA size to ~10**5 geoms. if i'm correct, runnig this notebook overwrites files in `data/{fuacode}/original/*.parquet`, ie we provide already clipped networks as raw data (but it's different to the `bananas` repo where we took it from)
* `remove_degree_2_nodes.ipynb` - removing degree 2 nodes from FUA road networks. this is what generated the files in `data/{fua}/no_degree_2`. 

suggestion for both of them: how about moving this to a subfolder `preprocess`, and add a comment in the first markdown cell saying that this notebook doesn't have to be run (as the generated input is already provided)?

**exploration of different simplification methods**

* `cityseer_*.ipynb`
* `momepy.ipynb`
* `osmnx.ipynb`
* `parenx.ipynb` & `parenx-run.sh` 

suggestion for all of them: rename into `method_{methodname}.ipynb` or `explore_method_{methodname}.ipynb` or similar

**(slightly outdated) simplification protocols**

* `simplification_*.ipynb` (5 notebooks)

suggestion is to replace them with one up-to-date notebook that runs sgeop on the original input data, calling it `method_sgeop.ipynb` (or whichever name convention we agree upon for the other methods) 

**(historically relevant) typology exploration notebooks**

* `typology-*.ipynb`(5 notebooks)

suggestion is to move them to a subfolder called `typology-exploration` or the like

**evaluation**

* `evaluate_h3cells.ipynb`

working on this currently, this will also generate the plots for the paper where we show comparisons between different methods; it might make sense to have one notebook each for comparing manual vs. method outcomes, mirroring the naming convention we choose for the `methods` notebooks (for example, having `methods-osmnx.ipynb` where OSMnx simplification is run -- and `evaluation-osmnx.ipynb` where OSMnx simplification is evaluated)

**use cases**

* `usecases.ipynb` – not sure what to do with this, in its current form it could be replaced by a json file, but also i think this is superseded by what we have in the hackmd, #50 ?

**Comment by anastassiavybornova** [comment]
oooor another option, brainstorming with myself here, how about having `/notebooks/` subfolders:
* preprocessing
* methods
* evaluation
* usecases 
or the like?

**Comment by jGaboardi** [comment]
> suggestion for all of them: delete? or move to an archive folder?

Probably best to keep in an archive for now.

**Comment by anastassiavybornova** [comment]
and finally, `clustering.ipynb`: quote from first cell: _Whether it will actualy work, no one knows. We also have no idea which variables shall be measured._ :D where should this one live?

**Comment by martinfleis** [comment]
Agree with everything you said and with _how about having /notebooks/ subfolders:_ even more.

Clustering was a wrong direction. Archive.

**Comment by anastassiavybornova** [comment]
cool, will reorder & PR now
