### ISSUE TITLE
generate sgeop data

### ISSUE THREAD

**Issue by anastassiavybornova** [uscuni/simplification#183]
notebook `method-sgeop.ipynb` that takes data from `data/{fua}/no_degree_2/`; runs `sgeop` on it; and saves to `data/{fua}/sgeop`. 

naively following the instructions in https://github.com/uscuni/sgeop would mean sticking with default parameters for all 6 FUAs. i suspect this will be trial and error until we adjusted parameters for each of the cities, @martinfleis  if you have any intuition on which ones to change from the get go let me know!

**Comment by martinfleis** [comment]
Not really.
