### ISSUE TITLE
decide where evaluation data should live

### ISSUE THREAD

**Issue by anastassiavybornova** [uscuni/simplification#185]
for the h3 hex evaluation, for each method (osmnx, parenx, sgeop etc) we will have a gdf of the corresponding grid. where do we want this evaluation data to live? 

(a) in `data/{fua}/evaluation/grid_{methodname}.gpkg`
(b) in `data/{fua}/{methodname}/grid.gpkg` (the `{methodname}` subfolders also contain the corresponding simplified gpkg)
(c) not in `data` but in a separate top-level `evaluation` folder

opinions appreciated :-*

**Comment by jGaboardi** [comment]
My opinion would be either (c) or (a), probably in the order of preference.

**Comment by martinfleis** [comment]
I'd go with c.

**Comment by anastassiavybornova** [comment]
(c) it is then!
