### ISSUE TITLE
update from `sgeop` to `neatnet`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#199]
Once the project, URLs, naming is updated from `sgeop` to `neatnet` over in the [package](https://github.com/uscuni/sgeop/), swap out sourcing over here.
* `pyproject.toml`
* `environment.yml`
* `ci/*`
* `core/*`
* `notebooks/*`
* etc...
* xref: https://github.com/uscuni/sgeop/issues/64

**Comment by anastassiavybornova** [comment]
also:
- [ ] write a new one-liner description of `neatnet` for the README

**Comment by jGaboardi** [comment]
xref -- https://github.com/uscuni/sgeop/issues/122
