### ISSUE TITLE
condense `read_<method>(fua)` down to `read_results(fua, method)`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#214]
As per @anastassiavybornova 's [suggestion](https://github.com/uscuni/simplification/pull/201#issuecomment-2512199684), we might want to condense the following down to something like `read_results()`:
* [`read_manual()`](https://github.com/uscuni/simplification/blob/2210d764b9f4b5147e91aecb87b995a09dc22781/core/utils.py#L85)
* [`read_cityseer()`](https://github.com/uscuni/simplification/blob/2210d764b9f4b5147e91aecb87b995a09dc22781/core/utils.py#L94)
* [`read_osmnx`](https://github.com/uscuni/simplification/blob/2210d764b9f4b5147e91aecb87b995a09dc22781/core/utils.py#L105)
* [`read_parenx()`](https://github.com/uscuni/simplification/blob/2210d764b9f4b5147e91aecb87b995a09dc22781/core/utils.py#L116)
* [`read_neatnet()`](https://github.com/uscuni/simplification/blob/2210d764b9f4b5147e91aecb87b995a09dc22781/core/utils.py#L131)

Something like:

```python
def read_results(
    fua: int | str, method: str, proj_crs: str | int | pyproj.CRS
) -> geopandas.GeoDataFrame:
    """Read results parquet format.

    Parameters
    -----------
    fua : int | str
        Code or name of FUA.
    method : str
        Simplification method used.
    proj_crs : str | int | pyproj.CRS
        Projected CRS information.

    Returns
    --------
    geopandas.GeoDataFrame
        Simplified results from ``fua`` by ``method``.
    """

    return (
        geopandas.read_parquet(_fua_path(fua, method))
        .explode(ingore_index=True, index_parts=False)
        .to_crs(proj_crs)
    )

read_results('Aleppo', 'manual')
read_results('Aleppo', 'cityseer')
read_results('Aleppo', 'osmnx')
read_results('Aleppo', 'parent-skeleton')
read_results('Aleppo', 'parent-voronoi')
read_results('Aleppo', 'neatnet')
```

What do yall think?
* [x] yes
* [ ] no

cc @martinfleis

**Comment by martinfleis** [comment]
I don't think it matters. Do whatever you like :)

**Comment by jGaboardi** [comment]
> I don't think it matters. Do whatever you like

You sound like a parent at wit's end. LOL

**Comment by anastassiavybornova** [comment]
@jGaboardi  I think it's a great idea and encourage you to go ahead!

Trying to sound like the other parent but I also really mean it

**Comment by martinfleis** [comment]
@jGaboardi go ask mom.
