### ISSUE TITLE
move anything from `notebooks/typology/*` into `notebooks/archive/typology/*`?

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#215]
I want to finish up #177 (which will also close out #175) , in doing so completely removing all modules in the [`algorithms`](https://github.com/uscuni/simplification/tree/main/core/algorithms) subpackage. As far as I can tell, the only stuff left using anything from `algorithms/` are the notebooks in `typology/`.

* I am curious if we want to migrate any of them into `notebooks/archive/typology/*`?
* Since all that functionality is baked into `neatnet` do we even just want to plop them into a `notebooks/archive/typology/*` without any updates?

(Bullet 2 is by far the lighter lift)

cc @martinfleis @anastassiavybornova

**Comment by martinfleis** [comment]
Those were exploratory so I'm fine with dumping them to archive. We could add a note that if someone really wants to rerun those, they can checkout older commit.
