### ISSUE TITLE
starting to "packagize" -- need a name

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#54]
xref #38 

As discussed today, I will start to build our infrastructure up & out since our work is maturing. Although it can be changed in the future if we want, it would be good if we had at least a preliminary name for the package to put in the `pyproject.toml`, etc.

Please edit / fill in the list below with ideas (or simply tell me if yall have already determined the name) @martinfleis @anastassiavybornova 

#### name ideas
* [X] `core` - passing vote

**Comment by martinfleis** [comment]
What about calling it simply `core`, given it is core of our work here? 

Tangential thought - I am starting to think whether the optimal end result is having these tools merged in momepy or releasing it separately. We are now contributing building preprocessing over to `geoplanar` and if we could delegate the core of preprocessing from momepy elsewhere, it may help keeping momepy more focused. Something to think about.

**Comment by jGaboardi** [comment]
* I am OK with `core` especially for now - just need a name at the moment.
* I always forget about `geoplanar` and wonder why Serge never wanted it to be part of PySAL. Any idea on that? Maybe you can press him on that next week.

**Comment by martinfleis** [comment]
> I always forget about geoplanar and wonder why Serge never wanted it to be part of PySAL. Any idea on that?

It was very much alpha prototype. We're pushing it to get something more stable. I'll check with him.
