### ISSUE TITLE
[infra] turn on `codecov` & `pre-commit` for repo

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#58]
@martinfleis Can you turn on `codecov` & `pre-commit` for this repo?

**Comment by jGaboardi** [comment]
@martinfleis What do you think about this?

**Comment by martinfleis** [comment]
I have turned on both. I think

**Comment by jGaboardi** [comment]
Not sure the `codecov` is working properly -- the [badge on README](https://github.com/uscuni/simplification/blob/main/README.md) is `unknown`.

Shall just remove that `codecov` badge? This isn't worth spinning our wheels over.

**Comment by martinfleis** [comment]
yeah

**Comment by jGaboardi** [comment]
closed via #72
