### ISSUE TITLE
future of `code/*`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#67]
We should decide the future of the `code/*` directory. Probably 2 ways forward reasonably:

1. Keep `code/*` and only have notebooks there
2. Rename `code/*`to something else and only have notebooks there

These are exactly the same thing...

Any other thoughts?

**Comment by martinfleis** [comment]
Any reason for renaming?

**Comment by anastassiavybornova** [comment]
since both reasonable ways imply only having notebooks there, how about renaming to `notebooks`? since "code" is arguably found in other folders too (i guess that was your reasoning too, james?) but i'm fine with whatever

**Comment by jGaboardi** [comment]
@anastassiavybornova Yeah, that's what I was thinking. Plus I am getting tired of having an extra step to tab-complete to the directory 😅 . Double plus even when simply ready the top dir content it can be easy to confuse `code` with `core`

**Comment by jGaboardi** [comment]
I'm going with renaming to `notebooks/` and apply that to #66
