### ISSUE TITLE
add docstring and test for `core/geometry.py`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#73]
* add docstring and test for `core/geometry.py`

**Comment by martinfleis** [comment]
heeey, that is unfair, there's a docstring :D

**Comment by jGaboardi** [comment]
OK --> "Jame needs to feel relevant and useful by ensuring unnecessary completeness on Martin's great docstring"

**Comment by martinfleis** [comment]
I'll take that :D

**Comment by jGaboardi** [comment]
@martinfleis Is this expected behavior?

```python
In [1]: import shapely, core
   ...: polygon = shapely.Polygon(
   ...:     (((0,0), (10,0), (10,10), (0,10), (0,0)))
   ...: )
   ...: line = shapely.LineString(((5,5), (100,5)))
   ...: core.geometry.is_within(line, polygon)
Out[1]: True
```

Basically, a small box where a line starts within the box, but the overwhelming majority of the line is outside the box. I interpret the `tol` parameter to relax the tolerance just a bit to handle cases where a line is *mostly* within a polygon.

**Comment by martinfleis** [comment]
Nope, that is not expected.

**Comment by jGaboardi** [comment]
found the bug

**Comment by jGaboardi** [comment]
https://github.com/uscuni/simplification/blob/fcae9daab634bf963a4b364f2980d89720b54c23/core/geometry.py#L8

**Comment by jGaboardi** [comment]
`tol` should be `-1e6`
