### ISSUE TITLE
OK to add tests for `algorithms/common.py`?

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#79]
Do we think the functionality of [`algorithms/common.py`](https://github.com/uscuni/simplification/blob/main/core/algorithms/common.py) will potentially change due to the stuff happening in `momepy`[^1][^2], or is it safe to start adding tests, etc. for it?

[^1]: https://github.com/pysal/momepy/issues/629
[^2]: https://github.com/pysal/momepy/pull/630

**Comment by martinfleis** [comment]
I think that he outcome may change little bit. I'd wait.

**Comment by jGaboardi** [comment]
I might build the bones of testing for it (instance type and geometry type, stuff like that); then fill out tests with expected values after the COINS implementation is settled.

**Comment by anastassiavybornova** [comment]
+1 for waiting once the coins refactoring is done (and obviously +1 for building the bones already, can't hurt)
