### ISSUE TITLE
Get Lovelace et al workflow(s)

### ISSUE THREAD

**Issue by martinfleis** [uscuni/simplification#8]
It seems that the code has been moved to its own package here https://github.com/anisotropi4/parenx

**Comment by anastassiavybornova** [comment]
see PR https://github.com/uscuni/simplification/pull/27

**Comment by jGaboardi** [comment]
@anastassiavybornova Should this be closed out now or are further explorations needed?

**Comment by anastassiavybornova** [comment]
we have the workflow in place and tested it on at least one of our use case cities; it works but is not ideal; and we already know what the problems are ("wobbly" lines, and computationally very costly, and many places in which it introduces artifacts) if we want to showcase the problems in the paper we will need to do some more processing/evaluation. so i think this particular issue can be closed (if we later will have a separate one for comparing/evaluating different approaches anyways)
