### ISSUE TITLE
failing CI due to `matplotlib==3.9.0`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#86]
Seems to maybe be some strange new behavior in `matplotlib==3.9.0` that is causing a [CI failure](https://github.com/uscuni/simplification/actions/runs/9761382410/job/26942291523#step:7:112). I tested this on both `geopandas==1.0.0` and `geopandas==1.0.1`, both were successful on `matplotlib==3.8.4` and both failed on `matplotlib==3.9.0`. Very odd that actual values would differ (see legend).

```
E           matplotlib.testing.exceptions.ImageComparisonFailure: images not close (RMS 33.877):
E           	result_images\test_viz_h3_hex\test_viz_h3_hex_plot_analysis.png
E           	result_images\test_viz_h3_hex\test_viz_h3_hex_plot_analysis-expected.png
E           	result_images\test_viz_h3_hex\test_viz_h3_hex_plot_analysis-failed-diff.png

C:\Users\runneradmin\micromamba\envs\py311_simplification-latest\Lib\contextlib.py:81: ImageComparisonFailure
```

<img width="1419" alt="strange_matplotlib" src="https://github.com/uscuni/simplification/assets/8590583/c6bdb18f-e648-40ef-b64a-cc38b3f1d144">

**Comment by anastassiavybornova** [comment]
Can it have something to do with normalization of scale? Only the scales in the 2 plots are different: on the left it goes from 0 to 3 (or so) and on the right it's much more fine grained (from 0.9 to 1.1), so i think the values are the same (if you look closely, the greyish stuff on the left - has values close to 1 - so does the blueish stuff on the right)  

but this one: https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.CenteredNorm.html doesn't seem to have changed from 3.8.x to 3.9 , so not sure where else the rescaling could be happening

**Comment by jGaboardi** [comment]
Looking back on this now, something seems to have changed deep in `matplotlib.colors.CenteredNorm` or maybe even `matplotlib.colors.Normalize` (or even deeper...), but I haven't been able to determine exactly what...

I can still reproduce the plot "as it should be" when downgrading to `matplotlib==3.8.4`, but the scaling is altered in any version after that.

***2 low-hanging fruit solutions:***
  1. pin `matplotlib==3.8.4` and keep current color schema (I think this color range is much more communicative)
  2. adopt the new color schema of (not a fan)

Other option is continue digging in `matplotlib` for what actually change, or file a bug report over there.

Thoughts?

**Comment by martinfleis** [comment]
I don't think this is expected change in behaviour and shall be reported as a regression to matplotlib.

**Comment by jGaboardi** [comment]
non-update -- @anastassiavybornova @martinfleis 

I have not been able to reproduce with a MWE. These 2 [gists](https://gist.github.com/jGaboardi/a618ffefcdc59f9f4cfc59fc459e9246) - first `matplotlib==3.8.4` then `matplotlib==3.9.1` - return equivalent results with the following code.

```python
%load_ext watermark
%watermark

import matplotlib
import numpy

%watermark -iv

values = (
    numpy.random.default_rng(850)
    .uniform(low=.01, high=2.9, size=10)
)

centered_norm = matplotlib.colors.CenteredNorm(vcenter=1)
centered_norm(values)
```

Any ideas for further inquiry would be greatly appreciated.

**Comment by martinfleis** [comment]
What if you use the actual values from the test rather than a random uniform distribution?

**Comment by jGaboardi** [comment]
* passing test with [`matplotlib==3.8.4`](https://github.com/uscuni/simplification/actions/runs/9979400401/job/27578442962?pr=80#step:7:120)
* failing test with [`matplotlib==3.9.1`](https://github.com/uscuni/simplification/actions/runs/9979400401/job/27578443228?pr=80#step:7:120)

**Comment by jGaboardi** [comment]
> What if you use the actual values from the test rather than a random uniform distribution?

Good idea. I'll try that next.

**Comment by jGaboardi** [comment]
@martinfleis @anastassiavybornova 

I have produced a (nearly) MWE, and to be honest, I am even more stumped as to what's going on. These two new minimal gists each:
* have the exact same package version except `matplotlib`
* create 4 random uniform values similar to those from our hex problem
* demonstrate that the `CenteredNorm` values are appropriately scaled
* plots
   * 4 points
   * 4 linestrings
   * 4 polygons
* [`matplotlib 3.8.4`](https://gist.github.com/jGaboardi/b90fc05674a1df92c118d79dc8fea513)
* [`matplotlib 3.9.1`](https://gist.github.com/jGaboardi/172f82647086ff4e6090acb0ede3ab7c)
* What we noticed happening for polygons is also happening for linestrings, but also the problem affects both point plotting for both versions.
* However, the actual calculated values of `CenteredNorm()` are equivalent in both versions of `matplotlib`
* Since both notebooks are running `geopandas==1.0.1` my hypothesis is some method for accessing those scaled in `CenteredNorm()` in `matplotlib` itself must be slightly off, but I have not been able to track down where from the [commit history](https://github.com/matplotlib/matplotlib/commits/main/lib/matplotlib/colors.py) over there.

| plot respects `norm=CenteredNorm()` | `matplotlib==3.8.4` | `matplotlib==3.9.1` | 
| --- | --- | --- |
| points | ❌ | ❌  |
| linestrings | ✅ | ❌  |
| polygons | ✅ | ❌  |

**Comment by martinfleis** [comment]
Just report it there.

**Comment by jGaboardi** [comment]
https://github.com/matplotlib/matplotlib/issues/28601

**Comment by jGaboardi** [comment]
* This seems to have actually been a bug in `matplotlib==3.8` that *was fixed* leading to the new results.
* As for the function & plots, I will in that again and see about adapting the color schema to reflect that which we could see with the "bug" version

@anastassiavybornova

**Comment by martinfleis** [comment]
Does it actually matter how the plots look like? Maybe we're just fine with the stats based on the values, no?

**Comment by jGaboardi** [comment]
> Does it actually matter how the plots look like?

I'm OK going the "new" (old) color schema - less work trying figure out new stuff. I will update the image comparison values accordingly.
