### ISSUE TITLE
Do a lit review search if there are other methods

### ISSUE THREAD

**Issue by martinfleis** [uscuni/simplification#9]
* Strictly defined terminology?

**Comment by jGaboardi** [comment]
I'll keep this open since we are still writing the paper.

**Comment by anastassiavybornova** [comment]
status quo:
* osmnx
* parenx
* cityseer
* momepy (? - it is mentioned but are we using it to compare as method for simplification?)
* (SNman - i want to look into it to see if it makes sense to include)

**Comment by anastassiavybornova** [comment]
* https://github.com/VictoriaDhmn/OSMNetFusion (logic is based on OSM tags so not useable for our purpose, but check if should be mentioned)

**Comment by jGaboardi** [comment]
> * https://github.com/VictoriaDhmn/OSMNetFusion (logic is based on OSM tags so not useable for our purpose, but check if should be mentioned)

I put this link in the OverLeaf.

**Comment by jGaboardi** [comment]
Closing this issue out since we are not actively working on manuscript.
