### ISSUE TITLE
`test_remove_degree_2_nodes` failure

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/simplification#99]
* [This failure](https://github.com/uscuni/simplification/actions/runs/10023912023/job/27705340454?pr=98#step:7:298) is happening across all environments and appear to be due to an [update in `momepy`](https://github.com/pysal/momepy/pull/642)
* I will investigate and update tests as needed.

```
FAILED core/tests/test_utils.py::test_remove_degree_2_nodes - AssertionError: GeoDataFrame shape mismatch, left: (46952, 1), right: (46190, 1).
Left columns: Index(['geometry'], dtype='object'), right columns: Index(['geometry'], dtype='object')
```

xref #90

**Comment by martinfleis** [comment]
New is likely correct
